#!/bin/sh

exec docker run \
    --rm \
    --tty \
    --interactive \
    --device=/dev/net/tun \
    --name=openvpn-client \
    --cap-add=NET_ADMIN \
    --env OVPN_FILE=yhome.ovpn \
    --env DNS_SERVER="192.168.8.1" \
    --publish 127.0.0.1:1080:1080 \
    --volume "$PWD/ovpn:/etc/openvpn/:ro" \
    --sysctl net.ipv6.conf.all.disable_ipv6=0 \
    ziony/openvpn-client